/*
 * This file is generated by jOOQ.
*/
package ru.adkazankov.jooq_crud.db.pg_catalog.routines;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;

import ru.adkazankov.jooq_crud.db.pg_catalog.PgCatalog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgLastCommittedXact extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1981699400;

    /**
     * The parameter <code>pg_catalog.pg_last_committed_xact.xid</code>.
     */
    public static final Parameter<Long> XID = createParameter("xid", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>pg_catalog.pg_last_committed_xact.timestamp</code>.
     */
    public static final Parameter<OffsetDateTime> TIMESTAMP = createParameter("timestamp", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, false, false);

    /**
     * Create a new routine call instance
     */
    public PgLastCommittedXact() {
        super("pg_last_committed_xact", PgCatalog.PG_CATALOG);

        addOutParameter(XID);
        addOutParameter(TIMESTAMP);
    }

    /**
     * Get the <code>xid</code> parameter OUT value from the routine
     */
    public Long getXid() {
        return get(XID);
    }

    /**
     * Get the <code>timestamp</code> parameter OUT value from the routine
     */
    public OffsetDateTime getTimestamp() {
        return get(TIMESTAMP);
    }
}
