/*
 * This file is generated by jOOQ.
*/
package ru.adkazankov.jooq_crud.db.public_;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.adkazankov.jooq_crud.db.public_.tables.Author;
import ru.adkazankov.jooq_crud.db.public_.tables.Film;
import ru.adkazankov.jooq_crud.db.public_.tables.records.AuthorRecord;
import ru.adkazankov.jooq_crud.db.public_.tables.records.FilmRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AuthorRecord, Integer> IDENTITY_AUTHOR = Identities0.IDENTITY_AUTHOR;
    public static final Identity<FilmRecord, Integer> IDENTITY_FILM = Identities0.IDENTITY_FILM;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> AUTHOR_PKEY = UniqueKeys0.AUTHOR_PKEY;
    public static final UniqueKey<FilmRecord> FILM_PKEY = UniqueKeys0.FILM_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<FilmRecord, AuthorRecord> FILM__FILM_AUTHOR_ID_FKEY = ForeignKeys0.FILM__FILM_AUTHOR_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AuthorRecord, Integer> IDENTITY_AUTHOR = Internal.createIdentity(Author.AUTHOR, Author.AUTHOR.ID);
        public static Identity<FilmRecord, Integer> IDENTITY_FILM = Internal.createIdentity(Film.FILM, Film.FILM.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthorRecord> AUTHOR_PKEY = Internal.createUniqueKey(Author.AUTHOR, "author_pkey", Author.AUTHOR.ID);
        public static final UniqueKey<FilmRecord> FILM_PKEY = Internal.createUniqueKey(Film.FILM, "film_pkey", Film.FILM.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<FilmRecord, AuthorRecord> FILM__FILM_AUTHOR_ID_FKEY = Internal.createForeignKey(ru.adkazankov.jooq_crud.db.public_.Keys.AUTHOR_PKEY, Film.FILM, "film__film_author_id_fkey", Film.FILM.AUTHOR_ID);
    }
}
